minimize:
  module: conserver-link-minimize
  options:
    minimization_model: "gpt-4o-mini"
    minimization_config:
      dialog:
        - fields_to_minimize: ["body"]
      analysis:
        - fields_to_minimize: ["body"]
minimize_fields:
  - "SSN:"
  - "Social Security Number:"
  - "Credit Card:"
  - "Account Number:"
  - "Routing Number:"
  - "Password:"
  - "PIN:"
  - "Date of Birth:"
