redact:
  module: conserver-link-redact
  options:
    redaction_model: "gpt-4o-mini"
    redaction_config:
      dialog:
        - fields_to_redact: ["body"]
      analysis:
        - fields_to_redact: ["body"]
