redact:
  module: conserver-link-redact
  options:
    redaction_model: "gpt-4o-mini"
    redaction_config:
      dialog:
        - fields_to_redact: ["body"]
      analysis:
        - fields_to_redact: ["body"]
redact_patterns:
  - "SSN:"
  - "Social Security Number:"
  - "Credit Card:"
  - "Account Number:"
  - "Routing Number:"
  - "Password:"
  - "PIN:"
  - "Date of Birth:"
